name: covector version or publish
on:
  push:
    branches:
      - v2

jobs:
  covector:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: cargo login
        run: cargo login ${{ secrets.ORG_CRATES_IO_TOKEN }}

      - name: git config
        run: |
          git config --global user.name "${{ github.event.pusher.name }}"
          git config --global user.email "${{ github.event.pusher.email }}"

      - name: install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0

      - name: covector version-or-publish
        uses: jbolda/covector/packages/action@covector-v0
        id: covector
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: "version-or-publish"
          createRelease: true

      - name: create pull request
        id: cpr
        if: steps.covector.outputs.commandRan == 'version'
        uses: tauri-apps/create-pull-request@v3
        with:
          title: "Publish New Versions (v2)"
          labels: "version updates"
          branch: "release-v2"
          body: ${{ steps.covector.outputs.change }}
