name: Clippy

on:
  push:
    branches:
      - v2
  pull_request:
    branches:
      - v2

jobs:
  clippy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: install webkit2gtk
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.1

      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Install clippy with stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Run clippy
        run: cargo clippy --manifest-path=Cargo.toml --all-targets --all-features -- -D warnings
